server:
  port: 8083
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lorde9030@gmail.com
    password: amyk uynq pvsh cjyd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/notification-api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: admin
  jpa:
    hibernate:
      #ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
      

     